/**
 * Public surface of `@cad/proto`. The buf-generated files under `../gen/ts/`
 * are regenerated by `pnpm --filter @cad/proto gen` (chained into `build`).
 *
 * Two export styles, both intentional:
 *
 *   1. Per-service value namespaces (`IncidentV1`, `HealthV1`) — for the
 *      gRPC clients, services, and enum constants. e.g.
 *        `new IncidentV1.IncidentServiceClient(addr, creds)`
 *        `IncidentV1.Severity.HIGH`
 *
 *   2. Flat *type-only* re-exports of the message interfaces — because
 *      ts-proto generates each message as BOTH `interface X` AND
 *      `const X: MessageFns<X>`, so `IncidentV1.OpenRequest` resolves
 *      to the const in type position. Flat type-only access dodges the
 *      ambiguity: `import type { OpenRequest } from '@cad/proto'`.
 */

export type {
  AuditActor,
  AuditEvent,
  AuditTarget,
  GetByTargetRequest,
  GetByTargetResponse,
  QueryRequest,
  QueryResponse,
} from '../gen/ts/cad/audit/v1/audit.js';
export * as AuditV1 from '../gen/ts/cad/audit/v1/audit.js';
export type {
  ListSeededOperatorsRequest,
  ListSeededOperatorsResponse,
  LoginRequest,
  LoginResponse,
  Operator,
  RefreshRequest,
  RefreshResponse,
  RevokeSessionRequest,
  RevokeSessionResponse,
  SeededOperator,
  ValidateTokenRequest,
  ValidateTokenResponse,
} from '../gen/ts/cad/auth/v1/auth.js';
export * as AuthV1 from '../gen/ts/cad/auth/v1/auth.js';
export * from '../gen/ts/cad/common/v1/geo.js';
export type { CheckRequest, CheckResponse } from '../gen/ts/cad/common/v1/health.js';
export * as HealthV1 from '../gen/ts/cad/common/v1/health.js';
export type {
  Recommendation,
  RecommendedUnit,
  RecommendUnitsRequest,
  RecommendUnitsResponse,
} from '../gen/ts/cad/dispatch/v1/dispatch.js';
export * as DispatchV1 from '../gen/ts/cad/dispatch/v1/dispatch.js';
export type {
  NearestKRequest,
  NearestKResponse,
  UnitDistance,
} from '../gen/ts/cad/geo/v1/geo.js';
export * as GeoV1 from '../gen/ts/cad/geo/v1/geo.js';
export type {
  AiTriageSuggestion,
  CancelRequest,
  CancelResponse,
  DeclareMajorRequest,
  DeclareMajorResponse,
  DispatchRequest,
  DispatchResponse,
  GetHistoryRequest,
  GetHistoryResponse,
  GetRequest,
  GetResponse,
  Incident,
  IncidentHistoryEntry,
  ListOpenRequest,
  ListOpenResponse,
  OpenRequest,
  OpenResponse,
  RecordUnitArrivalRequest,
  RecordUnitArrivalResponse,
  ResolveRequest,
  ResolveResponse,
  TriageRequest,
  TriageResponse,
} from '../gen/ts/cad/incident/v1/incident.js';
export * as IncidentV1 from '../gen/ts/cad/incident/v1/incident.js';
export type {
  GetTrackRequest,
  GetTrackResponse,
  GetUnitRequest,
  GetUnitResponse,
  ListUnitsRequest,
  ListUnitsResponse,
  RegisterUnitRequest,
  RegisterUnitResponse,
  TrackPoint,
  Unit,
  UpdateLocationRequest,
  UpdateLocationResponse,
  UpdateStatusRequest,
  UpdateStatusResponse,
} from '../gen/ts/cad/resource/v1/resource.js';
export * as ResourceV1 from '../gen/ts/cad/resource/v1/resource.js';
// service.triage — Phase 5 PR 3a. The RPC's request/response messages follow
// buf STANDARD's method-prefixed convention (`ClassifyRequest` /
// `ClassifyResponse`), which also dodges the flat-surface collision with
// `cad.incident.v1.TriageRequest` (the incident.triage state-transition
// request) without aliasing.
export type {
  ClassifyRequest,
  ClassifyResponse,
} from '../gen/ts/cad/triage/v1/triage.js';
export * as TriageV1 from '../gen/ts/cad/triage/v1/triage.js';

// Hand-rolled health constants kept for any callers still using the v0
// scaffold from before codegen landed. New code should use
// `HealthV1.HealthServiceClient` etc.
export const SERVING = 'SERVING' as const;
export const NOT_SERVING = 'NOT_SERVING' as const;
export type ServingStatus = typeof SERVING | typeof NOT_SERVING;
