/**
 * Public surface of `@cad/proto`. The buf-generated files under `../gen/ts/`
 * are regenerated by `pnpm --filter @cad/proto gen` (chained into `build`),
 * and we re-export them under per-service namespaces so the package root
 * stays tidy and forward-compatible.
 *
 * Pattern: `import { IncidentV1 } from '@cad/proto';`
 *          `const client = new IncidentV1.IncidentServiceClient(addr, creds);`
 *          `if (incident.severity === IncidentV1.Severity.CRITICAL) ...`
 */

export * from '../gen/ts/cad/common/v1/geo.js';
export * as HealthV1 from '../gen/ts/cad/common/v1/health.js';
export * as IncidentV1 from '../gen/ts/cad/incident/v1/incident.js';

// Hand-rolled health constants kept for any callers still using the v0
// scaffold from before codegen landed. New code should use
// `HealthV1.HealthServiceClient` etc.
export const SERVING = 'SERVING' as const;
export const NOT_SERVING = 'NOT_SERVING' as const;
export type ServingStatus = typeof SERVING | typeof NOT_SERVING;
