import { createTheme, createThemeContract } from '@vanilla-extract/css';

/**
 * The token contract. Every token is declared here so consuming code can
 * reference `vars.<category>.<key>` with type safety, regardless of which
 * theme is active. Themes (light / normal / dark) are mappings of these
 * contract keys to concrete values.
 *
 * Semantic groups:
 * - colors.tier        — service-tier identity (police / medical / fire)
 * - colors.severity    — severity scale s1..s5. Data is 4-level today
 *                        (low/medium/high/critical); tokens are 5-level so
 *                        the scale can grow. v1 mapping: low=s1, medium=s2,
 *                        high=s4, critical=s5; s3 reserved for future.
 * - colors.incidentState — per-state colour pairs for the incident state machine
 * - colors.unitStatus    — per-status colour pairs. Presence operator statuses
 *                          reuse this set (busy ↔ dispatched, off-duty ↔ outOfService).
 */
export const vars = createThemeContract({
  colors: {
    brand: {
      primary: null,
      primaryHover: null,
    },
    surface: {
      bg: null,
      bgElevated: null,
      sunken: null,
      raised: null,
      border: null,
      borderStrong: null,
      divider: null,
      overlay: null,
    },
    text: {
      default: null,
      muted: null,
      subtle: null,
      onBrand: null,
      onDanger: null,
      onAccent: null,
    },
    intent: {
      danger: null,
      warning: null,
      success: null,
      info: null,
      dangerBg: null,
      warningBg: null,
      successBg: null,
      infoBg: null,
    },
    tier: {
      police: null,
      medical: null,
      fire: null,
      policeBg: null,
      medicalBg: null,
      fireBg: null,
    },
    severity: {
      s1: null,
      s2: null,
      s3: null,
      s4: null,
      s5: null,
      s1Bg: null,
      s2Bg: null,
      s3Bg: null,
      s4Bg: null,
      s5Bg: null,
    },
    incidentState: {
      open: null,
      triaged: null,
      dispatched: null,
      enRoute: null,
      onScene: null,
      resolved: null,
      cancelled: null,
      openBg: null,
      triagedBg: null,
      dispatchedBg: null,
      enRouteBg: null,
      onSceneBg: null,
      resolvedBg: null,
      cancelledBg: null,
    },
    unitStatus: {
      available: null,
      dispatched: null,
      enRoute: null,
      onScene: null,
      outOfService: null,
      availableBg: null,
      dispatchedBg: null,
      enRouteBg: null,
      onSceneBg: null,
      outOfServiceBg: null,
    },
  },
  spacing: {
    '0': null,
    '2': null,
    '4': null,
    '8': null,
    '12': null,
    '16': null,
    '24': null,
    '32': null,
    '48': null,
    '64': null,
  },
  radii: {
    sm: null,
    md: null,
    lg: null,
    full: null,
  },
  typography: {
    body: null,
    heading: {
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      metric: null,
    },
    mono: null,
    monoSm: null,
    monoCaps: null,
  },
  shadows: {
    sm: null,
    md: null,
    elevated: null,
    inset: null,
    focusRing: null,
  },
  transitions: {
    fast: null,
    spring: null,
  },
  zIndex: {
    base: null,
    sticky: null,
    modal: null,
    toast: null,
  },
});

const baseTokens = {
  spacing: {
    '0': '0',
    '2': '2px',
    '4': '4px',
    '8': '8px',
    '12': '12px',
    '16': '16px',
    '24': '24px',
    '32': '32px',
    '48': '48px',
    '64': '64px',
  },
  radii: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  typography: {
    body: '14px/1.5 -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", sans-serif',
    heading: {
      xs: '600 11px/1.4 "JetBrains Mono", "SF Mono", Menlo, monospace',
      sm: '600 16px/1.4 -apple-system, BlinkMacSystemFont, "Inter", sans-serif',
      md: '600 20px/1.3 -apple-system, BlinkMacSystemFont, "Inter", sans-serif',
      lg: '700 28px/1.2 -apple-system, BlinkMacSystemFont, "Inter", sans-serif',
      xl: '700 36px/1.15 -apple-system, BlinkMacSystemFont, "Inter", sans-serif',
      metric: '600 30px/1.1 "JetBrains Mono", "SF Mono", Menlo, monospace',
    },
    mono: '13px/1.5 "JetBrains Mono", "SF Mono", Menlo, monospace',
    monoSm: '11px/1.4 "JetBrains Mono", "SF Mono", Menlo, monospace',
    monoCaps: '600 11px/1.4 "JetBrains Mono", "SF Mono", Menlo, monospace',
  },
  transitions: {
    fast: '120ms ease-out',
    spring: '180ms cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  zIndex: {
    base: '0',
    sticky: '100',
    modal: '1000',
    toast: '2000',
  },
};

export const lightTheme = createTheme(vars, {
  ...baseTokens,
  colors: {
    brand: {
      primary: '#0a84ff',
      primaryHover: '#0066cc',
    },
    surface: {
      bg: '#ffffff',
      bgElevated: '#f7f9fc',
      sunken: '#eef1f5',
      raised: '#ffffff',
      border: '#e4e8ee',
      borderStrong: '#c9d0d9',
      divider: '#eef1f5',
      overlay: 'rgba(13, 17, 23, 0.4)',
    },
    text: {
      default: '#0d1117',
      muted: '#3b424a',
      subtle: '#57606a',
      onBrand: '#ffffff',
      onDanger: '#ffffff',
      onAccent: '#0d1117',
    },
    intent: {
      danger: '#cf222e',
      warning: '#bf8700',
      success: '#1a7f37',
      info: '#0a84ff',
      dangerBg: '#fde8ea',
      warningBg: '#fdf3d6',
      successBg: '#dcfae6',
      infoBg: '#e0efff',
    },
    tier: {
      police: '#1d4ed8',
      medical: '#15803d',
      fire: '#b91c1c',
      policeBg: '#e0e9ff',
      medicalBg: '#dcfae6',
      fireBg: '#fde2e2',
    },
    severity: {
      s1: '#1a7f37',
      s2: '#bf8700',
      s3: '#d97706',
      s4: '#cf222e',
      s5: '#7e1d1d',
      s1Bg: '#dcfae6',
      s2Bg: '#fdf3d6',
      s3Bg: '#fde7c4',
      s4Bg: '#fde8ea',
      s5Bg: '#f7d5d5',
    },
    incidentState: {
      open: '#bf8700',
      triaged: '#0a84ff',
      dispatched: '#0a84ff',
      enRoute: '#0a84ff',
      onScene: '#1a7f37',
      resolved: '#57606a',
      cancelled: '#57606a',
      openBg: '#fdf3d6',
      triagedBg: '#e0efff',
      dispatchedBg: '#e0efff',
      enRouteBg: '#cfe2ff',
      onSceneBg: '#dcfae6',
      resolvedBg: '#eef1f5',
      cancelledBg: '#eef1f5',
    },
    unitStatus: {
      available: '#1a7f37',
      dispatched: '#0a84ff',
      enRoute: '#bf8700',
      onScene: '#bf8700',
      outOfService: '#57606a',
      availableBg: '#dcfae6',
      dispatchedBg: '#e0efff',
      enRouteBg: '#fdf3d6',
      onSceneBg: '#fdf3d6',
      outOfServiceBg: '#eef1f5',
    },
  },
  shadows: {
    sm: '0 1px 2px rgba(13, 17, 23, 0.06)',
    md: '0 4px 8px rgba(13, 17, 23, 0.08)',
    elevated: '0 8px 24px rgba(13, 17, 23, 0.12)',
    inset: 'inset 0 1px 0 rgba(13, 17, 23, 0.06)',
    focusRing: '0 0 0 3px rgba(10, 132, 255, 0.4)',
  },
});

export const normalTheme = createTheme(vars, {
  ...baseTokens,
  colors: {
    brand: {
      primary: '#2563eb',
      primaryHover: '#1d4ed8',
    },
    surface: {
      bg: '#f9fafb',
      bgElevated: '#ffffff',
      sunken: '#eef0f3',
      raised: '#ffffff',
      border: '#e5e7eb',
      borderStrong: '#cbd1d8',
      divider: '#eef0f3',
      overlay: 'rgba(17, 24, 39, 0.5)',
    },
    text: {
      default: '#111827',
      muted: '#374151',
      subtle: '#4b5563',
      onBrand: '#ffffff',
      onDanger: '#ffffff',
      onAccent: '#111827',
    },
    intent: {
      danger: '#dc2626',
      warning: '#d97706',
      success: '#16a34a',
      info: '#2563eb',
      dangerBg: '#fee2e2',
      warningBg: '#fef3c7',
      successBg: '#dcfce7',
      infoBg: '#dbeafe',
    },
    tier: {
      police: '#1d4ed8',
      medical: '#15803d',
      fire: '#b91c1c',
      policeBg: '#dbeafe',
      medicalBg: '#dcfce7',
      fireBg: '#fee2e2',
    },
    severity: {
      s1: '#16a34a',
      s2: '#d97706',
      s3: '#ea580c',
      s4: '#dc2626',
      s5: '#7f1d1d',
      s1Bg: '#dcfce7',
      s2Bg: '#fef3c7',
      s3Bg: '#fed7aa',
      s4Bg: '#fee2e2',
      s5Bg: '#fecaca',
    },
    incidentState: {
      open: '#d97706',
      triaged: '#2563eb',
      dispatched: '#2563eb',
      enRoute: '#2563eb',
      onScene: '#16a34a',
      resolved: '#6b7280',
      cancelled: '#6b7280',
      openBg: '#fef3c7',
      triagedBg: '#dbeafe',
      dispatchedBg: '#dbeafe',
      enRouteBg: '#bfdbfe',
      onSceneBg: '#dcfce7',
      resolvedBg: '#eef0f3',
      cancelledBg: '#eef0f3',
    },
    unitStatus: {
      available: '#16a34a',
      dispatched: '#2563eb',
      enRoute: '#d97706',
      onScene: '#d97706',
      outOfService: '#6b7280',
      availableBg: '#dcfce7',
      dispatchedBg: '#dbeafe',
      enRouteBg: '#fef3c7',
      onSceneBg: '#fef3c7',
      outOfServiceBg: '#eef0f3',
    },
  },
  shadows: {
    sm: '0 1px 2px rgba(17, 24, 39, 0.06)',
    md: '0 4px 8px rgba(17, 24, 39, 0.08)',
    elevated: '0 8px 24px rgba(17, 24, 39, 0.12)',
    inset: 'inset 0 1px 0 rgba(17, 24, 39, 0.06)',
    focusRing: '0 0 0 3px rgba(37, 99, 235, 0.4)',
  },
});

// Dark theme — tuned toward an ops/ATC console palette. Cool slate
// backgrounds (not GitHub-dark blue-gray), cyan-leaning brand.
export const darkTheme = createTheme(vars, {
  ...baseTokens,
  colors: {
    brand: {
      primary: '#38bdf8',
      primaryHover: '#7dd3fc',
    },
    surface: {
      bg: '#0b0f14',
      bgElevated: '#11161d',
      sunken: '#070a0e',
      raised: '#1a212b',
      border: '#2a3441',
      borderStrong: '#3a4757',
      divider: '#1c2430',
      overlay: 'rgba(0, 0, 0, 0.65)',
    },
    text: {
      default: '#e6edf3',
      muted: '#b1bac4',
      subtle: '#7d8590',
      onBrand: '#031620',
      onDanger: '#ffffff',
      onAccent: '#e6edf3',
    },
    intent: {
      danger: '#f87171',
      warning: '#fbbf24',
      success: '#4ade80',
      info: '#38bdf8',
      dangerBg: '#2a1517',
      warningBg: '#2a1f0a',
      successBg: '#0e2418',
      infoBg: '#0e2230',
    },
    tier: {
      police: '#60a5fa',
      medical: '#4ade80',
      fire: '#fb923c',
      policeBg: '#0e2230',
      medicalBg: '#0e2418',
      fireBg: '#2a1808',
    },
    severity: {
      s1: '#4ade80',
      s2: '#fbbf24',
      s3: '#fb923c',
      s4: '#f87171',
      s5: '#ef4444',
      s1Bg: '#0e2418',
      s2Bg: '#2a1f0a',
      s3Bg: '#2a1808',
      s4Bg: '#2a1517',
      s5Bg: '#341013',
    },
    incidentState: {
      open: '#fbbf24',
      triaged: '#38bdf8',
      dispatched: '#38bdf8',
      enRoute: '#7dd3fc',
      onScene: '#4ade80',
      resolved: '#7d8590',
      cancelled: '#7d8590',
      openBg: '#2a1f0a',
      triagedBg: '#0e2230',
      dispatchedBg: '#0e2230',
      enRouteBg: '#102a3a',
      onSceneBg: '#0e2418',
      resolvedBg: '#1c2430',
      cancelledBg: '#1c2430',
    },
    unitStatus: {
      available: '#4ade80',
      dispatched: '#38bdf8',
      enRoute: '#fbbf24',
      onScene: '#fb923c',
      outOfService: '#7d8590',
      availableBg: '#0e2418',
      dispatchedBg: '#0e2230',
      enRouteBg: '#2a1f0a',
      onSceneBg: '#2a1808',
      outOfServiceBg: '#1c2430',
    },
  },
  shadows: {
    sm: '0 1px 2px rgba(0, 0, 0, 0.4)',
    md: '0 4px 8px rgba(0, 0, 0, 0.4)',
    elevated: '0 8px 24px rgba(0, 0, 0, 0.5)',
    inset: 'inset 0 1px 0 rgba(255, 255, 255, 0.04)',
    focusRing: '0 0 0 3px rgba(56, 189, 248, 0.45)',
  },
});

// Apps apply one of the theme classes (lightTheme / normalTheme / darkTheme)
// to the root element. Switching themes is a className swap — vars resolve
// transparently because they're contract references.
